using System.Collections.Generic;

namespace juniorassembler
{
    // a lookup table for known symbols in EPROM Bank 1 - function or variable addresses
    internal class SymbolMapBank1 : IScope
    {
        public string find(ushort address)
        {
            string ret;
            return allSymbolsBank1.TryGetValue(address, out ret) ? ret : null;
        }

        private static Dictionary<int, string> allSymbolsBank1 = new Dictionary<int, string>
        {
            { 0x2000, "drucker.writeStarTty" },
            { 0x205C, "drucker.outStar" },
            { 0x2069, "drucker.initStar" },
            { 0x207f, "drucker.UmsetzTabelle" },
            { 0x2100, "drucker.initStarTtyMode" },
            { 0x2118, "drucker.initStarNotTty" },
            { 0x2138, "drucker.writeplus" },
            { 0x214E, "drucker.delay" },
            { 0x2159, "drucker.pieps" },
            { 0x2176, "drucker.druckeVideoSchirm" },
            { 0x2181, "drucker.manuellDruckeVideoSchirm" },

            { 0x2205, "hexedit.writeMoni" },
            { 0x2250, "hexedit.initVideo" },
            { 0x225E, "hexedit.blankVideo" },
            { 0x2284, "hexedit.cursInc" },
            { 0x2297, "hexedit.cursDown" },
            { 0x22C9, "hexedit.cursUp" },
            { 0x22CF, "hexedit.cursDec" },
            { 0x22FD, "hexedit.cursAdrSql" },
            { 0x231D, "hexedit.setCursSql" },
            { 0x2339, "hexedit.setCurs" },
            { 0x234E, "hexedit.WRVideo" },
            { 0x2364, "hexedit.Home" },
            { 0x2370, "hexedit.clear" },
            { 0x23A1, "hexedit.block.rangeIn" },
            { 0x23AF, "hexedit.block.rangeOut" },
            { 0x23BD, "hexedit.block.setCursIn" },
            { 0x23CC, "hexedit.block.setCursOut" },
            { 0x23DB, "hexedit.block.incCursIn" },
            { 0x23E2, "hexedit.block.incCursOut" },
            { 0x23E9, "hexedit.block.initInFile" },
            { 0x23F2, "hexedit.block.initOutFile" },
            { 0x23FE, "hexedit.block.readFile" },
            { 0x2409, "hexedit.block.writeFile" },
            { 0x241D, "hexedit.InMoni" },
            { 0x242B, "hexedit.getHex" },
            { 0x2431, "hexedit.TasteMitWdh" },
            { 0x2449, "hexedit.readHex" },
            { 0x2460, "hexedit.read" },
            { 0x2463, "hexedit.write" },
            { 0x2466, "hexedit.openOutVideo" },
            { 0x2469, "hexedit.openOutVideo2" },
            { 0x246F, "hexedit.openOutStarTty" },
            { 0x2478, "hexedit.openOutFile" },
            { 0x248B, "hexedit.openInHexKb" },
            { 0x24A4, "hexedit.openInFile" },
            { 0x24B7, "hexedit.loescheRestZeileUCursDown" },
            { 0x24C9, "hexedit.2Blanks" },
            { 0x24CE, "hexedit.Blank" },
            { 0x24D4, "hexedit.CR" },
            { 0x24E2, "hexedit.Nibble" },
            { 0x24EF, "hexedit.byteDru" },
            { 0x2503, "hexedit.lwriteVonBis" },
            { 0x2506, "hexedit.writeVonBis" },
            { 0x2514, "hexedit.writeBlock" },
            { 0x2533, "hexedit.readVonBis" },
            { 0x2560, "dump.dump(unused)" },
            { 0x2599, "hexedit.Grossbuchstaben" },
            { 0x25A5, "bs.KPUe" },
            { 0x2600, "hexedit.decoder" },
            { 0x2640, "hexedit.sucheInET" },
            { 0x2668, "hexedit.suche" },
            { 0x26A8, "hexedit.disAssembler" },
            { 0x26F6, "hexedit.testDisAssembler" },
            { 0x2770, "hexedit.TestUndTransfer" },
            { 0x2798, "hexedit.LineDel" },
            { 0x27BB, "hexedit.LineIns" },
            { 0x2814, "hexedit.berechneBis" },
            { 0x284B, "hexedit.INS" },
            { 0x2885, "hexedit.Delete" },
            { 0x28A0, "hexedit.zeigeAusser" },
            { 0x28D0, "hexedit.grenzeAendern" },
            { 0x2910, "hexedit.copy" },
            { 0x2978, "hexedit.hardcopy" },
            { 0x29DE, "hexedit.CTRL?" },
            { 0x2A90, "hexedit.Adr" },
            { 0x2AE8, "hexedit.home" },
            { 0x2B00, "hexedit.Blaettern" },
            { 0x2B20, "hexedit.PlusmBl" },
            { 0x2B43, "hexedit.MinusmBl" },
            { 0x2B60, "hexedit.reBlaettern" },
            { 0x2BC0, "hexedit.nibble" },
            { 0x2BC6, "hexedit.wandle" },
            { 0x2BD8, "hexedit.GetByte" },
            { 0x2BE3, "hexedit.RestByte" },
            { 0x2C00, "hexedit.berechneZeiNrAb23" },
            { 0x2C04, "hexedit.berechneZeiNrAb0" },
            { 0x2C06, "hexedit.berechneZeiNrAbRx" },
            { 0x2CA0, "hexedit.restZeile" },
            { 0x2CE0, "hexedit.cursFromPointPlusZeige" },
            { 0x2CE8, "hexedit.cursFromPoint" },
            { 0x2D45, "hexedit.BerechneUDisplay" },
            { 0x2D48, "hexedit.displayuC" },
            { 0x2D50, "hexedit.display" },
            { 0x2DAA, "hexedit.Vorlauf" },
            { 0x2DD0, "hexedit.hexIn" },
            { 0x2DD6, "hexedit.AsciiIn" },
            { 0x2E30, "hexedit.pointFromCursPPlusZeige" },
            { 0x2E38, "hexedit.pointFromCurs" },
            { 0x2E80, "hexedit.VerschiebeDialog" },
            { 0x2EED, "hexedit.keyRight" },
            { 0x2F00, "hexedit.main" },
            { 0x2FC1, "hexedit.MiniInitBs(unused!)" },
            { 0x2FD0, "hexedit.keyLeft" },
            { 0x2FE4, "hexedit.keyDown" },
            { 0x2FEA, "hexedit.keyUp" },
            { 0x3294, "hexedit.cursIncPlus" },
            { 0x33A0, "keyb2.Umsetztabelle" },
            { 0x34DD, "keyb2.initTastatur2" },
            { 0x35A7, "keyb2.readTastatur2OrHex" },
            { 0x35DD, "keyb2.initTastatur2AndHex" },
            { 0x35F0, "keyb2.sampleHex" },
            { 0x38D0, "rkv.initBs" },
            { 0x3A6B, "rkv.initUB" },
            { 0x3C90, "hexedit.nextCurAd" },
            { 0x3E40, "hexedit.Transfer2" },
            { 0x4000, "Texteditor" },
            { 0x4F30, "Directory" },
            { 0x5000, "Floppy" },
        };
    }
}